import { PERMISSIONS } from './permissions.js';

export const ROLE_PERMISSIONS = Object.freeze({
  OWNER: Object.values(PERMISSIONS),
  MANAGER: [
    PERMISSIONS.BUSINESS_INVITE_MEMBER,
    PERMISSIONS.PRODUCTS_CREATE,
    PERMISSIONS.PRODUCTS_UPDATE,
    PERMISSIONS.CATEGORIES_MANAGE,
  ],
  CASHIER: [],
  INVENTORY_MANAGER: [],
  ACCOUNTANT: [],
});
